python train.py \
--dataset=shapenet \
--train_size=-1 \
--val_size=-1 \
--test_size=-1 \
--epoch=50 \
--verbose=100 \
--learning_rate=2e-4 \
--weight_decay=1e-4 \
--batch_size=256 \
--gpu=2 \
--attention=spatial \
--evaluation=true
